sudo: false
language: android
jdk:
# https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks
  - openjdk8
  - oraclejdk8
  - oraclejdk11
  - openjdk11

# http://docs.travis-ci.com/user/languages/android/
android:
  components:
    - build-tools-29.0.2
    - android-29

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

before_script:
  - chmod +x gradlew
#  - echo no | android create avd --force -n test -t android-10 --abi armeabi
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

# Currently connectedCheck fails, so don't run unit test on Emulator for now. Issue:
# com.android.builder.testing.ConnectedDevice > hasTests[test(AVD) - 2.3.3] FAILED
# No tests found.

script:
  - TERM=dumb ./gradlew check
